//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "BlobEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.BlobEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "BooleanEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.BooleanEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "DateTimeEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.DateTimeEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "DoubleEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.DoubleEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_EntityAttribute", "EntityTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityTable), "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.EntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "FloatEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.FloatEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "IntegerEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.IntegerEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "MediumStringEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.MediumStringEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_StringEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "StringEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.StringEntityAttributeTable), true)]
[assembly: EdmRelationshipAttribute("Entity", "fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Scaglia.Entity.DAL.EntityAttributeTable), "TinyStringEntityAttributeTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Scaglia.Entity.DAL.TinyStringEntityAttributeTable), true)]

#endregion

namespace Scaglia.Entity.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MySqlEntityDatabaseContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MySqlEntityDatabaseContext object using the connection string found in the 'MySqlEntityDatabaseContext' section of the application configuration file.
        /// </summary>
        public MySqlEntityDatabaseContext() : base("name=MySqlEntityDatabaseContext", "MySqlEntityDatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MySqlEntityDatabaseContext object.
        /// </summary>
        public MySqlEntityDatabaseContext(string connectionString) : base(connectionString, "MySqlEntityDatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MySqlEntityDatabaseContext object.
        /// </summary>
        public MySqlEntityDatabaseContext(EntityConnection connection) : base(connection, "MySqlEntityDatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<BlobEntityAttributeTable> BlobEntityAttributeTable
        {
            get
            {
                if ((_BlobEntityAttributeTable == null))
                {
                    _BlobEntityAttributeTable = base.CreateObjectSet<BlobEntityAttributeTable>("BlobEntityAttributeTable");
                }
                return _BlobEntityAttributeTable;
            }
        }
        private ObjectSet<BlobEntityAttributeTable> _BlobEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<BooleanEntityAttributeTable> BooleanEntityAttributeTable
        {
            get
            {
                if ((_BooleanEntityAttributeTable == null))
                {
                    _BooleanEntityAttributeTable = base.CreateObjectSet<BooleanEntityAttributeTable>("BooleanEntityAttributeTable");
                }
                return _BooleanEntityAttributeTable;
            }
        }
        private ObjectSet<BooleanEntityAttributeTable> _BooleanEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<DateTimeEntityAttributeTable> DateTimeEntityAttributeTable
        {
            get
            {
                if ((_DateTimeEntityAttributeTable == null))
                {
                    _DateTimeEntityAttributeTable = base.CreateObjectSet<DateTimeEntityAttributeTable>("DateTimeEntityAttributeTable");
                }
                return _DateTimeEntityAttributeTable;
            }
        }
        private ObjectSet<DateTimeEntityAttributeTable> _DateTimeEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<DoubleEntityAttributeTable> DoubleEntityAttributeTable
        {
            get
            {
                if ((_DoubleEntityAttributeTable == null))
                {
                    _DoubleEntityAttributeTable = base.CreateObjectSet<DoubleEntityAttributeTable>("DoubleEntityAttributeTable");
                }
                return _DoubleEntityAttributeTable;
            }
        }
        private ObjectSet<DoubleEntityAttributeTable> _DoubleEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<EntityAttributeTable> EntityAttributeTable
        {
            get
            {
                if ((_EntityAttributeTable == null))
                {
                    _EntityAttributeTable = base.CreateObjectSet<EntityAttributeTable>("EntityAttributeTable");
                }
                return _EntityAttributeTable;
            }
        }
        private ObjectSet<EntityAttributeTable> _EntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<EntityTable> EntityTable
        {
            get
            {
                if ((_EntityTable == null))
                {
                    _EntityTable = base.CreateObjectSet<EntityTable>("EntityTable");
                }
                return _EntityTable;
            }
        }
        private ObjectSet<EntityTable> _EntityTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<FloatEntityAttributeTable> FloatEntityAttributeTable
        {
            get
            {
                if ((_FloatEntityAttributeTable == null))
                {
                    _FloatEntityAttributeTable = base.CreateObjectSet<FloatEntityAttributeTable>("FloatEntityAttributeTable");
                }
                return _FloatEntityAttributeTable;
            }
        }
        private ObjectSet<FloatEntityAttributeTable> _FloatEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<IntegerEntityAttributeTable> IntegerEntityAttributeTable
        {
            get
            {
                if ((_IntegerEntityAttributeTable == null))
                {
                    _IntegerEntityAttributeTable = base.CreateObjectSet<IntegerEntityAttributeTable>("IntegerEntityAttributeTable");
                }
                return _IntegerEntityAttributeTable;
            }
        }
        private ObjectSet<IntegerEntityAttributeTable> _IntegerEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<MediumStringEntityAttributeTable> MediumStringEntityAttributeTable
        {
            get
            {
                if ((_MediumStringEntityAttributeTable == null))
                {
                    _MediumStringEntityAttributeTable = base.CreateObjectSet<MediumStringEntityAttributeTable>("MediumStringEntityAttributeTable");
                }
                return _MediumStringEntityAttributeTable;
            }
        }
        private ObjectSet<MediumStringEntityAttributeTable> _MediumStringEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<StringEntityAttributeTable> StringEntityAttributeTable
        {
            get
            {
                if ((_StringEntityAttributeTable == null))
                {
                    _StringEntityAttributeTable = base.CreateObjectSet<StringEntityAttributeTable>("StringEntityAttributeTable");
                }
                return _StringEntityAttributeTable;
            }
        }
        private ObjectSet<StringEntityAttributeTable> _StringEntityAttributeTable;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        internal ObjectSet<TinyStringEntityAttributeTable> TinyStringEntityAttributeTable
        {
            get
            {
                if ((_TinyStringEntityAttributeTable == null))
                {
                    _TinyStringEntityAttributeTable = base.CreateObjectSet<TinyStringEntityAttributeTable>("TinyStringEntityAttributeTable");
                }
                return _TinyStringEntityAttributeTable;
            }
        }
        private ObjectSet<TinyStringEntityAttributeTable> _TinyStringEntityAttributeTable;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlobEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlobEntityAttributeTable(BlobEntityAttributeTable blobEntityAttributeTable)
        {
            base.AddObject("BlobEntityAttributeTable", blobEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BooleanEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBooleanEntityAttributeTable(BooleanEntityAttributeTable booleanEntityAttributeTable)
        {
            base.AddObject("BooleanEntityAttributeTable", booleanEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DateTimeEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDateTimeEntityAttributeTable(DateTimeEntityAttributeTable dateTimeEntityAttributeTable)
        {
            base.AddObject("DateTimeEntityAttributeTable", dateTimeEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DoubleEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoubleEntityAttributeTable(DoubleEntityAttributeTable doubleEntityAttributeTable)
        {
            base.AddObject("DoubleEntityAttributeTable", doubleEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityAttributeTable(EntityAttributeTable entityAttributeTable)
        {
            base.AddObject("EntityAttributeTable", entityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityTable(EntityTable entityTable)
        {
            base.AddObject("EntityTable", entityTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FloatEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFloatEntityAttributeTable(FloatEntityAttributeTable floatEntityAttributeTable)
        {
            base.AddObject("FloatEntityAttributeTable", floatEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IntegerEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIntegerEntityAttributeTable(IntegerEntityAttributeTable integerEntityAttributeTable)
        {
            base.AddObject("IntegerEntityAttributeTable", integerEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediumStringEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediumStringEntityAttributeTable(MediumStringEntityAttributeTable mediumStringEntityAttributeTable)
        {
            base.AddObject("MediumStringEntityAttributeTable", mediumStringEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StringEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStringEntityAttributeTable(StringEntityAttributeTable stringEntityAttributeTable)
        {
            base.AddObject("StringEntityAttributeTable", stringEntityAttributeTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinyStringEntityAttributeTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinyStringEntityAttributeTable(TinyStringEntityAttributeTable tinyStringEntityAttributeTable)
        {
            base.AddObject("TinyStringEntityAttributeTable", tinyStringEntityAttributeTable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="BlobEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlobEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlobEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static BlobEntityAttributeTable CreateBlobEntityAttributeTable(global::System.Int32 id)
        {
            BlobEntityAttributeTable blobEntityAttributeTable = new BlobEntityAttributeTable();
            blobEntityAttributeTable.Id = id;
            return blobEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Value
        {
            get
            {
                return StructuralObject.GetValidValue(_Value);
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Byte[] _Value;
        partial void OnValueChanging(global::System.Byte[] value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="BooleanEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BooleanEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BooleanEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static BooleanEntityAttributeTable CreateBooleanEntityAttributeTable(global::System.Int32 id)
        {
            BooleanEntityAttributeTable booleanEntityAttributeTable = new BooleanEntityAttributeTable();
            booleanEntityAttributeTable.Id = id;
            return booleanEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Boolean> _Value;
        partial void OnValueChanging(Nullable<global::System.Boolean> value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="DateTimeEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DateTimeEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DateTimeEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DateTimeEntityAttributeTable CreateDateTimeEntityAttributeTable(global::System.Int32 id)
        {
            DateTimeEntityAttributeTable dateTimeEntityAttributeTable = new DateTimeEntityAttributeTable();
            dateTimeEntityAttributeTable.Id = id;
            return dateTimeEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.DateTime> _Value;
        partial void OnValueChanging(Nullable<global::System.DateTime> value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="DoubleEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DoubleEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DoubleEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DoubleEntityAttributeTable CreateDoubleEntityAttributeTable(global::System.Int32 id)
        {
            DoubleEntityAttributeTable doubleEntityAttributeTable = new DoubleEntityAttributeTable();
            doubleEntityAttributeTable.Id = id;
            return doubleEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Double> _Value;
        partial void OnValueChanging(Nullable<global::System.Double> value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="EntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EntityAttributeTable CreateEntityAttributeTable(global::System.Int32 id)
        {
            EntityAttributeTable entityAttributeTable = new EntityAttributeTable();
            entityAttributeTable.Id = id;
            return entityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntity
        {
            get
            {
                return _IdEntity;
            }
            set
            {
                OnIdEntityChanging(value);
                ReportPropertyChanging("IdEntity");
                _IdEntity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntity");
                OnIdEntityChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntity;
        partial void OnIdEntityChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int16> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int16> value);
        partial void OnTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_BlobEntityAttribute", "BlobEntityAttributeTable")]
        public EntityCollection<BlobEntityAttributeTable> BlobEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlobEntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "BlobEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlobEntityAttributeTable>("Entity.fk_IdEntity_BlobEntityAttribute", "BlobEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_BooleanEntityAttribute", "BooleanEntityAttributeTable")]
        public EntityCollection<BooleanEntityAttributeTable> BooleanEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BooleanEntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "BooleanEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BooleanEntityAttributeTable>("Entity.fk_IdEntity_BooleanEntityAttribute", "BooleanEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_DateTimeEntityAttribute", "DateTimeEntityAttributeTable")]
        public EntityCollection<DateTimeEntityAttributeTable> DateTimeEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DateTimeEntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "DateTimeEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DateTimeEntityAttributeTable>("Entity.fk_IdEntity_DateTimeEntityAttribute", "DateTimeEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_DoubleEntityAttribute", "DoubleEntityAttributeTable")]
        public EntityCollection<DoubleEntityAttributeTable> DoubleEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DoubleEntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "DoubleEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DoubleEntityAttributeTable>("Entity.fk_IdEntity_DoubleEntityAttribute", "DoubleEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_EntityAttribute", "EntityTable")]
        public EntityTable EntityTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTable>("Entity.fk_IdEntity_EntityAttribute", "EntityTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTable>("Entity.fk_IdEntity_EntityAttribute", "EntityTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityTable> EntityTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTable>("Entity.fk_IdEntity_EntityAttribute", "EntityTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityTable>("Entity.fk_IdEntity_EntityAttribute", "EntityTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_FloatEntityAttribute", "FloatEntityAttributeTable")]
        public EntityCollection<FloatEntityAttributeTable> FloatEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FloatEntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "FloatEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FloatEntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "FloatEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_IntegerEntityAttribute", "IntegerEntityAttributeTable")]
        public EntityCollection<IntegerEntityAttributeTable> IntegerEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IntegerEntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "IntegerEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IntegerEntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "IntegerEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_MediumEntityAttribute", "MediumStringEntityAttributeTable")]
        public EntityCollection<MediumStringEntityAttributeTable> MediumStringEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MediumStringEntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "MediumStringEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MediumStringEntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "MediumStringEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_StringEntityAttribute", "StringEntityAttributeTable")]
        public EntityCollection<StringEntityAttributeTable> StringEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StringEntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "StringEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StringEntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "StringEntityAttributeTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_TinyStringEntityAttribute", "TinyStringEntityAttributeTable")]
        public EntityCollection<TinyStringEntityAttributeTable> TinyStringEntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TinyStringEntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "TinyStringEntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TinyStringEntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "TinyStringEntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="EntityTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EntityTable CreateEntityTable(global::System.Int32 id)
        {
            EntityTable entityTable = new EntityTable();
            entityTable.Id = id;
            return entityTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdSystem
        {
            get
            {
                return _IdSystem;
            }
            set
            {
                OnIdSystemChanging(value);
                ReportPropertyChanging("IdSystem");
                _IdSystem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSystem");
                OnIdSystemChanged();
            }
        }
        private Nullable<global::System.Int32> _IdSystem;
        partial void OnIdSystemChanging(Nullable<global::System.Int32> value);
        partial void OnIdSystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdOrganization
        {
            get
            {
                return _IdOrganization;
            }
            set
            {
                OnIdOrganizationChanging(value);
                ReportPropertyChanging("IdOrganization");
                _IdOrganization = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdOrganization");
                OnIdOrganizationChanged();
            }
        }
        private Nullable<global::System.Int32> _IdOrganization;
        partial void OnIdOrganizationChanging(Nullable<global::System.Int32> value);
        partial void OnIdOrganizationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_EntityAttribute", "EntityAttributeTable")]
        public EntityCollection<EntityAttributeTable> EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityAttributeTable>("Entity.fk_IdEntity_EntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityAttributeTable>("Entity.fk_IdEntity_EntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="FloatEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FloatEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FloatEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static FloatEntityAttributeTable CreateFloatEntityAttributeTable(global::System.Int32 id)
        {
            FloatEntityAttributeTable floatEntityAttributeTable = new FloatEntityAttributeTable();
            floatEntityAttributeTable.Id = id;
            return floatEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Single> _Value;
        partial void OnValueChanging(Nullable<global::System.Single> value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_FloatEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="IntegerEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IntegerEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IntegerEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static IntegerEntityAttributeTable CreateIntegerEntityAttributeTable(global::System.Int32 id)
        {
            IntegerEntityAttributeTable integerEntityAttributeTable = new IntegerEntityAttributeTable();
            integerEntityAttributeTable.Id = id;
            return integerEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private Nullable<global::System.Int32> _Value;
        partial void OnValueChanging(Nullable<global::System.Int32> value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_IntegerEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="MediumStringEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediumStringEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediumStringEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MediumStringEntityAttributeTable CreateMediumStringEntityAttributeTable(global::System.Int32 id)
        {
            MediumStringEntityAttributeTable mediumStringEntityAttributeTable = new MediumStringEntityAttributeTable();
            mediumStringEntityAttributeTable.Id = id;
            return mediumStringEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_MediumEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="StringEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StringEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StringEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static StringEntityAttributeTable CreateStringEntityAttributeTable(global::System.Int32 id)
        {
            StringEntityAttributeTable stringEntityAttributeTable = new StringEntityAttributeTable();
            stringEntityAttributeTable.Id = id;
            return stringEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_StringEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_StringEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entity", Name="TinyStringEntityAttributeTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinyStringEntityAttributeTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinyStringEntityAttributeTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TinyStringEntityAttributeTable CreateTinyStringEntityAttributeTable(global::System.Int32 id)
        {
            TinyStringEntityAttributeTable tinyStringEntityAttributeTable = new TinyStringEntityAttributeTable();
            tinyStringEntityAttributeTable.Id = id;
            return tinyStringEntityAttributeTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEntityAttribute
        {
            get
            {
                return _IdEntityAttribute;
            }
            set
            {
                OnIdEntityAttributeChanging(value);
                ReportPropertyChanging("IdEntityAttribute");
                _IdEntityAttribute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEntityAttribute");
                OnIdEntityAttributeChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEntityAttribute;
        partial void OnIdEntityAttributeChanging(Nullable<global::System.Int32> value);
        partial void OnIdEntityAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entity", "fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable")]
        public EntityAttributeTable EntityAttributeTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityAttributeTable> EntityAttributeTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityAttributeTable>("Entity.fk_IdEntity_TinyStringEntityAttribute", "EntityAttributeTable", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
